/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * ApiAddFilesPostRequest
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ApiAddFilesPostRequest implements Parcelable {
  public static final String SERIALIZED_NAME_PACKAGE_ID = "package_id";
  @SerializedName(SERIALIZED_NAME_PACKAGE_ID)
  @javax.annotation.Nonnull
  private Integer packageId;

  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nonnull
  private List<String> links = new ArrayList<>();

  public ApiAddFilesPostRequest() {
  }

  public ApiAddFilesPostRequest packageId(@javax.annotation.Nonnull Integer packageId) {
    
    this.packageId = packageId;
    return this;
  }

  /**
   * package id
   * @return packageId
   */
  @javax.annotation.Nonnull

  public Integer getPackageId() {
    return packageId;
  }


  public void setPackageId(@javax.annotation.Nonnull Integer packageId) {
    this.packageId = packageId;
  }

  public ApiAddFilesPostRequest links(@javax.annotation.Nonnull List<String> links) {
    
    this.links = links;
    return this;
  }

  public ApiAddFilesPostRequest addLinksItem(String linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * list of urls
   * @return links
   */
  @javax.annotation.Nonnull

  public List<String> getLinks() {
    return links;
  }


  public void setLinks(@javax.annotation.Nonnull List<String> links) {
    this.links = links;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiAddFilesPostRequest apiAddFilesPostRequest = (ApiAddFilesPostRequest) o;
    return Objects.equals(this.packageId, apiAddFilesPostRequest.packageId) &&
        Objects.equals(this.links, apiAddFilesPostRequest.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageId, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiAddFilesPostRequest {\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(packageId);
    out.writeValue(links);
  }

  ApiAddFilesPostRequest(Parcel in) {
    packageId = (Integer)in.readValue(null);
    links = (List<String>)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<ApiAddFilesPostRequest> CREATOR = new Parcelable.Creator<ApiAddFilesPostRequest>() {
    public ApiAddFilesPostRequest createFromParcel(Parcel in) {
      return new ApiAddFilesPostRequest(in);
    }
    public ApiAddFilesPostRequest[] newArray(int size) {
      return new ApiAddFilesPostRequest[size];
    }
  };

}

