/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.pyload.android.openapi.model.Destination;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * ApiCheckAndAddPackagesPostRequest
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ApiCheckAndAddPackagesPostRequest implements Parcelable {
  public static final String SERIALIZED_NAME_LINKS = "links";
  @SerializedName(SERIALIZED_NAME_LINKS)
  @javax.annotation.Nonnull
  private List<String> links = new ArrayList<>();

  public static final String SERIALIZED_NAME_DEST = "dest";
  @SerializedName(SERIALIZED_NAME_DEST)
  @javax.annotation.Nullable
  private Destination dest = Destination.COLLECTOR;

  public ApiCheckAndAddPackagesPostRequest() {
  }

  public ApiCheckAndAddPackagesPostRequest links(@javax.annotation.Nonnull List<String> links) {
    
    this.links = links;
    return this;
  }

  public ApiCheckAndAddPackagesPostRequest addLinksItem(String linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * list of urls
   * @return links
   */
  @javax.annotation.Nonnull

  public List<String> getLinks() {
    return links;
  }


  public void setLinks(@javax.annotation.Nonnull List<String> links) {
    this.links = links;
  }

  public ApiCheckAndAddPackagesPostRequest dest(@javax.annotation.Nullable Destination dest) {
    
    this.dest = dest;
    return this;
  }

  /**
   * &#x60;Destination&#x60;
   * @return dest
   */
  @javax.annotation.Nullable

  public Destination getDest() {
    return dest;
  }


  public void setDest(@javax.annotation.Nullable Destination dest) {
    this.dest = dest;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiCheckAndAddPackagesPostRequest apiCheckAndAddPackagesPostRequest = (ApiCheckAndAddPackagesPostRequest) o;
    return Objects.equals(this.links, apiCheckAndAddPackagesPostRequest.links) &&
        Objects.equals(this.dest, apiCheckAndAddPackagesPostRequest.dest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(links, dest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiCheckAndAddPackagesPostRequest {\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    dest: ").append(toIndentedString(dest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(links);
    out.writeValue(dest);
  }

  ApiCheckAndAddPackagesPostRequest(Parcel in) {
    links = (List<String>)in.readValue(null);
    dest = (Destination)in.readValue(Destination.class.getClassLoader());
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<ApiCheckAndAddPackagesPostRequest> CREATOR = new Parcelable.Creator<ApiCheckAndAddPackagesPostRequest>() {
    public ApiCheckAndAddPackagesPostRequest createFromParcel(Parcel in) {
      return new ApiCheckAndAddPackagesPostRequest(in);
    }
    public ApiCheckAndAddPackagesPostRequest[] newArray(int size) {
      return new ApiCheckAndAddPackagesPostRequest[size];
    }
  };

}

