/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * ApiMoveFilesPostRequest
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ApiMoveFilesPostRequest implements Parcelable {
  public static final String SERIALIZED_NAME_FILE_IDS = "file_ids";
  @SerializedName(SERIALIZED_NAME_FILE_IDS)
  @javax.annotation.Nonnull
  private List<Integer> fileIds = new ArrayList<>();

  public static final String SERIALIZED_NAME_PACKAGE_ID = "package_id";
  @SerializedName(SERIALIZED_NAME_PACKAGE_ID)
  @javax.annotation.Nonnull
  private Integer packageId;

  public ApiMoveFilesPostRequest() {
  }

  public ApiMoveFilesPostRequest fileIds(@javax.annotation.Nonnull List<Integer> fileIds) {
    
    this.fileIds = fileIds;
    return this;
  }

  public ApiMoveFilesPostRequest addFileIdsItem(Integer fileIdsItem) {
    if (this.fileIds == null) {
      this.fileIds = new ArrayList<>();
    }
    this.fileIds.add(fileIdsItem);
    return this;
  }

  /**
   * list of file ids
   * @return fileIds
   */
  @javax.annotation.Nonnull

  public List<Integer> getFileIds() {
    return fileIds;
  }


  public void setFileIds(@javax.annotation.Nonnull List<Integer> fileIds) {
    this.fileIds = fileIds;
  }

  public ApiMoveFilesPostRequest packageId(@javax.annotation.Nonnull Integer packageId) {
    
    this.packageId = packageId;
    return this;
  }

  /**
   * destination package
   * @return packageId
   */
  @javax.annotation.Nonnull

  public Integer getPackageId() {
    return packageId;
  }


  public void setPackageId(@javax.annotation.Nonnull Integer packageId) {
    this.packageId = packageId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiMoveFilesPostRequest apiMoveFilesPostRequest = (ApiMoveFilesPostRequest) o;
    return Objects.equals(this.fileIds, apiMoveFilesPostRequest.fileIds) &&
        Objects.equals(this.packageId, apiMoveFilesPostRequest.packageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fileIds, packageId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiMoveFilesPostRequest {\n");
    sb.append("    fileIds: ").append(toIndentedString(fileIds)).append("\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(fileIds);
    out.writeValue(packageId);
  }

  ApiMoveFilesPostRequest(Parcel in) {
    fileIds = (List<Integer>)in.readValue(null);
    packageId = (Integer)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<ApiMoveFilesPostRequest> CREATOR = new Parcelable.Creator<ApiMoveFilesPostRequest>() {
    public ApiMoveFilesPostRequest createFromParcel(Parcel in) {
      return new ApiMoveFilesPostRequest(in);
    }
    public ApiMoveFilesPostRequest[] newArray(int size) {
      return new ApiMoveFilesPostRequest[size];
    }
  };

}

