/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import android.os.Parcelable;
import android.os.Parcel;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Destination
 */
@JsonAdapter(Destination.Adapter.class)
@SuppressWarnings("unchecked")
public enum Destination {
  
  COLLECTOR(0),
  
  QUEUE(1);

  private Integer value;

  Destination(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Destination fromValue(Integer value) {
    for (Destination b : Destination.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<Destination> {
    @Override
    public void write(final JsonWriter jsonWriter, final Destination enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Destination read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return Destination.fromValue(value);
    }
  }
}

