/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;
import android.os.Parcelable;
import android.os.Parcel;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DownloadStatus
 */
@JsonAdapter(DownloadStatus.Adapter.class)
@SuppressWarnings("unchecked")
public enum DownloadStatus {
  
  ABORTED(9),
  
  CUSTOM(11),
  
  DECRYPTING(10),
  
  DOWNLOADING(12),
  
  FAILED(8),
  
  FINISHED(0),
  
  OFFLINE(1),
  
  ONLINE(2),
  
  PROCESSING(13),
  
  QUEUED(3),
  
  SKIPPED(4),
  
  STARTING(7),
  
  TEMPOFFLINE(6),
  
  UNKNOWN(14),
  
  WAITING(5);

  private Integer value;

  DownloadStatus(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DownloadStatus fromValue(Integer value) {
    for (DownloadStatus b : DownloadStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<DownloadStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final DownloadStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DownloadStatus read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return DownloadStatus.fromValue(value);
    }
  }
}

