/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.pyload.android.openapi.model.DownloadStatus;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * DownloadInfo
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class DownloadInfo implements Parcelable {
  public static final String SERIALIZED_NAME_FID = "fid";
  @SerializedName(SERIALIZED_NAME_FID)
  @javax.annotation.Nonnull
  private Integer fid;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SPEED = "speed";
  @SerializedName(SERIALIZED_NAME_SPEED)
  @javax.annotation.Nonnull
  private Long speed;

  public static final String SERIALIZED_NAME_ETA = "eta";
  @SerializedName(SERIALIZED_NAME_ETA)
  @javax.annotation.Nonnull
  private Integer eta;

  public static final String SERIALIZED_NAME_FORMAT_ETA = "format_eta";
  @SerializedName(SERIALIZED_NAME_FORMAT_ETA)
  @javax.annotation.Nonnull
  private String formatEta;

  public static final String SERIALIZED_NAME_BLEFT = "bleft";
  @SerializedName(SERIALIZED_NAME_BLEFT)
  @javax.annotation.Nonnull
  private Long bleft;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  @javax.annotation.Nonnull
  private Long size;

  public static final String SERIALIZED_NAME_FORMAT_SIZE = "format_size";
  @SerializedName(SERIALIZED_NAME_FORMAT_SIZE)
  @javax.annotation.Nonnull
  private String formatSize;

  public static final String SERIALIZED_NAME_PERCENT = "percent";
  @SerializedName(SERIALIZED_NAME_PERCENT)
  @javax.annotation.Nonnull
  private Integer percent;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nonnull
  private DownloadStatus status;

  public static final String SERIALIZED_NAME_STATUSMSG = "statusmsg";
  @SerializedName(SERIALIZED_NAME_STATUSMSG)
  @javax.annotation.Nonnull
  private String statusmsg;

  public static final String SERIALIZED_NAME_FORMAT_WAIT = "format_wait";
  @SerializedName(SERIALIZED_NAME_FORMAT_WAIT)
  @javax.annotation.Nonnull
  private String formatWait;

  public static final String SERIALIZED_NAME_WAIT_UNTIL = "wait_until";
  @SerializedName(SERIALIZED_NAME_WAIT_UNTIL)
  @javax.annotation.Nonnull
  private Float waitUntil;

  public static final String SERIALIZED_NAME_PACKAGE_ID = "package_id";
  @SerializedName(SERIALIZED_NAME_PACKAGE_ID)
  @javax.annotation.Nonnull
  private Integer packageId;

  public static final String SERIALIZED_NAME_PACKAGE_NAME = "package_name";
  @SerializedName(SERIALIZED_NAME_PACKAGE_NAME)
  @javax.annotation.Nonnull
  private String packageName;

  public static final String SERIALIZED_NAME_PLUGIN = "plugin";
  @SerializedName(SERIALIZED_NAME_PLUGIN)
  @javax.annotation.Nonnull
  private String plugin;

  public static final String SERIALIZED_NAME_INFO = "info";
  @SerializedName(SERIALIZED_NAME_INFO)
  @javax.annotation.Nonnull
  private String info;

  public DownloadInfo() {
  }

  public DownloadInfo fid(@javax.annotation.Nonnull Integer fid) {
    
    this.fid = fid;
    return this;
  }

  /**
   * Get fid
   * @return fid
   */
  @javax.annotation.Nonnull

  public Integer getFid() {
    return fid;
  }


  public void setFid(@javax.annotation.Nonnull Integer fid) {
    this.fid = fid;
  }

  public DownloadInfo name(@javax.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }

  public DownloadInfo speed(@javax.annotation.Nonnull Long speed) {
    
    this.speed = speed;
    return this;
  }

  /**
   * Get speed
   * @return speed
   */
  @javax.annotation.Nonnull

  public Long getSpeed() {
    return speed;
  }


  public void setSpeed(@javax.annotation.Nonnull Long speed) {
    this.speed = speed;
  }

  public DownloadInfo eta(@javax.annotation.Nonnull Integer eta) {
    
    this.eta = eta;
    return this;
  }

  /**
   * Get eta
   * @return eta
   */
  @javax.annotation.Nonnull

  public Integer getEta() {
    return eta;
  }


  public void setEta(@javax.annotation.Nonnull Integer eta) {
    this.eta = eta;
  }

  public DownloadInfo formatEta(@javax.annotation.Nonnull String formatEta) {
    
    this.formatEta = formatEta;
    return this;
  }

  /**
   * Get formatEta
   * @return formatEta
   */
  @javax.annotation.Nonnull

  public String getFormatEta() {
    return formatEta;
  }


  public void setFormatEta(@javax.annotation.Nonnull String formatEta) {
    this.formatEta = formatEta;
  }

  public DownloadInfo bleft(@javax.annotation.Nonnull Long bleft) {
    
    this.bleft = bleft;
    return this;
  }

  /**
   * Get bleft
   * @return bleft
   */
  @javax.annotation.Nonnull

  public Long getBleft() {
    return bleft;
  }


  public void setBleft(@javax.annotation.Nonnull Long bleft) {
    this.bleft = bleft;
  }

  public DownloadInfo size(@javax.annotation.Nonnull Long size) {
    
    this.size = size;
    return this;
  }

  /**
   * Get size
   * @return size
   */
  @javax.annotation.Nonnull

  public Long getSize() {
    return size;
  }


  public void setSize(@javax.annotation.Nonnull Long size) {
    this.size = size;
  }

  public DownloadInfo formatSize(@javax.annotation.Nonnull String formatSize) {
    
    this.formatSize = formatSize;
    return this;
  }

  /**
   * Get formatSize
   * @return formatSize
   */
  @javax.annotation.Nonnull

  public String getFormatSize() {
    return formatSize;
  }


  public void setFormatSize(@javax.annotation.Nonnull String formatSize) {
    this.formatSize = formatSize;
  }

  public DownloadInfo percent(@javax.annotation.Nonnull Integer percent) {
    
    this.percent = percent;
    return this;
  }

  /**
   * Get percent
   * @return percent
   */
  @javax.annotation.Nonnull

  public Integer getPercent() {
    return percent;
  }


  public void setPercent(@javax.annotation.Nonnull Integer percent) {
    this.percent = percent;
  }

  public DownloadInfo status(@javax.annotation.Nonnull DownloadStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull

  public DownloadStatus getStatus() {
    return status;
  }


  public void setStatus(@javax.annotation.Nonnull DownloadStatus status) {
    this.status = status;
  }

  public DownloadInfo statusmsg(@javax.annotation.Nonnull String statusmsg) {
    
    this.statusmsg = statusmsg;
    return this;
  }

  /**
   * Get statusmsg
   * @return statusmsg
   */
  @javax.annotation.Nonnull

  public String getStatusmsg() {
    return statusmsg;
  }


  public void setStatusmsg(@javax.annotation.Nonnull String statusmsg) {
    this.statusmsg = statusmsg;
  }

  public DownloadInfo formatWait(@javax.annotation.Nonnull String formatWait) {
    
    this.formatWait = formatWait;
    return this;
  }

  /**
   * Get formatWait
   * @return formatWait
   */
  @javax.annotation.Nonnull

  public String getFormatWait() {
    return formatWait;
  }


  public void setFormatWait(@javax.annotation.Nonnull String formatWait) {
    this.formatWait = formatWait;
  }

  public DownloadInfo waitUntil(@javax.annotation.Nonnull Float waitUntil) {
    
    this.waitUntil = waitUntil;
    return this;
  }

  /**
   * Get waitUntil
   * @return waitUntil
   */
  @javax.annotation.Nonnull

  public Float getWaitUntil() {
    return waitUntil;
  }


  public void setWaitUntil(@javax.annotation.Nonnull Float waitUntil) {
    this.waitUntil = waitUntil;
  }

  public DownloadInfo packageId(@javax.annotation.Nonnull Integer packageId) {
    
    this.packageId = packageId;
    return this;
  }

  /**
   * Get packageId
   * @return packageId
   */
  @javax.annotation.Nonnull

  public Integer getPackageId() {
    return packageId;
  }


  public void setPackageId(@javax.annotation.Nonnull Integer packageId) {
    this.packageId = packageId;
  }

  public DownloadInfo packageName(@javax.annotation.Nonnull String packageName) {
    
    this.packageName = packageName;
    return this;
  }

  /**
   * Get packageName
   * @return packageName
   */
  @javax.annotation.Nonnull

  public String getPackageName() {
    return packageName;
  }


  public void setPackageName(@javax.annotation.Nonnull String packageName) {
    this.packageName = packageName;
  }

  public DownloadInfo plugin(@javax.annotation.Nonnull String plugin) {
    
    this.plugin = plugin;
    return this;
  }

  /**
   * Get plugin
   * @return plugin
   */
  @javax.annotation.Nonnull

  public String getPlugin() {
    return plugin;
  }


  public void setPlugin(@javax.annotation.Nonnull String plugin) {
    this.plugin = plugin;
  }

  public DownloadInfo info(@javax.annotation.Nonnull String info) {
    
    this.info = info;
    return this;
  }

  /**
   * Get info
   * @return info
   */
  @javax.annotation.Nonnull

  public String getInfo() {
    return info;
  }


  public void setInfo(@javax.annotation.Nonnull String info) {
    this.info = info;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DownloadInfo downloadInfo = (DownloadInfo) o;
    return Objects.equals(this.fid, downloadInfo.fid) &&
        Objects.equals(this.name, downloadInfo.name) &&
        Objects.equals(this.speed, downloadInfo.speed) &&
        Objects.equals(this.eta, downloadInfo.eta) &&
        Objects.equals(this.formatEta, downloadInfo.formatEta) &&
        Objects.equals(this.bleft, downloadInfo.bleft) &&
        Objects.equals(this.size, downloadInfo.size) &&
        Objects.equals(this.formatSize, downloadInfo.formatSize) &&
        Objects.equals(this.percent, downloadInfo.percent) &&
        Objects.equals(this.status, downloadInfo.status) &&
        Objects.equals(this.statusmsg, downloadInfo.statusmsg) &&
        Objects.equals(this.formatWait, downloadInfo.formatWait) &&
        Objects.equals(this.waitUntil, downloadInfo.waitUntil) &&
        Objects.equals(this.packageId, downloadInfo.packageId) &&
        Objects.equals(this.packageName, downloadInfo.packageName) &&
        Objects.equals(this.plugin, downloadInfo.plugin) &&
        Objects.equals(this.info, downloadInfo.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fid, name, speed, eta, formatEta, bleft, size, formatSize, percent, status, statusmsg, formatWait, waitUntil, packageId, packageName, plugin, info);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DownloadInfo {\n");
    sb.append("    fid: ").append(toIndentedString(fid)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("    formatEta: ").append(toIndentedString(formatEta)).append("\n");
    sb.append("    bleft: ").append(toIndentedString(bleft)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    formatSize: ").append(toIndentedString(formatSize)).append("\n");
    sb.append("    percent: ").append(toIndentedString(percent)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusmsg: ").append(toIndentedString(statusmsg)).append("\n");
    sb.append("    formatWait: ").append(toIndentedString(formatWait)).append("\n");
    sb.append("    waitUntil: ").append(toIndentedString(waitUntil)).append("\n");
    sb.append("    packageId: ").append(toIndentedString(packageId)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    plugin: ").append(toIndentedString(plugin)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(fid);
    out.writeValue(name);
    out.writeValue(speed);
    out.writeValue(eta);
    out.writeValue(formatEta);
    out.writeValue(bleft);
    out.writeValue(size);
    out.writeValue(formatSize);
    out.writeValue(percent);
    out.writeValue(status);
    out.writeValue(statusmsg);
    out.writeValue(formatWait);
    out.writeValue(waitUntil);
    out.writeValue(packageId);
    out.writeValue(packageName);
    out.writeValue(plugin);
    out.writeValue(info);
  }

  DownloadInfo(Parcel in) {
    fid = (Integer)in.readValue(null);
    name = (String)in.readValue(null);
    speed = (Long)in.readValue(null);
    eta = (Integer)in.readValue(null);
    formatEta = (String)in.readValue(null);
    bleft = (Long)in.readValue(null);
    size = (Long)in.readValue(null);
    formatSize = (String)in.readValue(null);
    percent = (Integer)in.readValue(null);
    status = (DownloadStatus)in.readValue(DownloadStatus.class.getClassLoader());
    statusmsg = (String)in.readValue(null);
    formatWait = (String)in.readValue(null);
    waitUntil = (Float)in.readValue(null);
    packageId = (Integer)in.readValue(null);
    packageName = (String)in.readValue(null);
    plugin = (String)in.readValue(null);
    info = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<DownloadInfo> CREATOR = new Parcelable.Creator<DownloadInfo>() {
    public DownloadInfo createFromParcel(Parcel in) {
      return new DownloadInfo(in);
    }
    public DownloadInfo[] newArray(int size) {
      return new DownloadInfo[size];
    }
  };

}

