/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * OldUserData
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class OldUserData implements Parcelable {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  @javax.annotation.Nullable
  private String email;

  public static final String SERIALIZED_NAME_ROLE = "role";
  @SerializedName(SERIALIZED_NAME_ROLE)
  @javax.annotation.Nullable
  private Integer role;

  public static final String SERIALIZED_NAME_PERMISSION = "permission";
  @SerializedName(SERIALIZED_NAME_PERMISSION)
  @javax.annotation.Nullable
  private Integer permission;

  public static final String SERIALIZED_NAME_TEMPLATE_NAME = "template_name";
  @SerializedName(SERIALIZED_NAME_TEMPLATE_NAME)
  @javax.annotation.Nullable
  private String templateName;

  public OldUserData() {
  }

  public OldUserData name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public OldUserData email(@javax.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable

  public String getEmail() {
    return email;
  }


  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }

  public OldUserData role(@javax.annotation.Nullable Integer role) {
    
    this.role = role;
    return this;
  }

  /**
   * Get role
   * @return role
   */
  @javax.annotation.Nullable

  public Integer getRole() {
    return role;
  }


  public void setRole(@javax.annotation.Nullable Integer role) {
    this.role = role;
  }

  public OldUserData permission(@javax.annotation.Nullable Integer permission) {
    
    this.permission = permission;
    return this;
  }

  /**
   * Get permission
   * @return permission
   */
  @javax.annotation.Nullable

  public Integer getPermission() {
    return permission;
  }


  public void setPermission(@javax.annotation.Nullable Integer permission) {
    this.permission = permission;
  }

  public OldUserData templateName(@javax.annotation.Nullable String templateName) {
    
    this.templateName = templateName;
    return this;
  }

  /**
   * Get templateName
   * @return templateName
   */
  @javax.annotation.Nullable

  public String getTemplateName() {
    return templateName;
  }


  public void setTemplateName(@javax.annotation.Nullable String templateName) {
    this.templateName = templateName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OldUserData oldUserData = (OldUserData) o;
    return Objects.equals(this.name, oldUserData.name) &&
        Objects.equals(this.email, oldUserData.email) &&
        Objects.equals(this.role, oldUserData.role) &&
        Objects.equals(this.permission, oldUserData.permission) &&
        Objects.equals(this.templateName, oldUserData.templateName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, email, role, permission, templateName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OldUserData {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(name);
    out.writeValue(email);
    out.writeValue(role);
    out.writeValue(permission);
    out.writeValue(templateName);
  }

  OldUserData(Parcel in) {
    name = (String)in.readValue(null);
    email = (String)in.readValue(null);
    role = (Integer)in.readValue(null);
    permission = (Integer)in.readValue(null);
    templateName = (String)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<OldUserData> CREATOR = new Parcelable.Creator<OldUserData>() {
    public OldUserData createFromParcel(Parcel in) {
      return new OldUserData(in);
    }
    public OldUserData[] newArray(int size) {
      return new OldUserData[size];
    }
  };

}

