/*
 * pyLoad API Documentation - OpenAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.pyload.android.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import android.os.Parcelable;
import android.os.Parcel;

/**
 * OnlineCheck
 */
@SuppressWarnings("unchecked")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class OnlineCheck implements Parcelable {
  public static final String SERIALIZED_NAME_RID = "rid";
  @SerializedName(SERIALIZED_NAME_RID)
  @javax.annotation.Nonnull
  private Integer rid;

  public static final String SERIALIZED_NAME_DATA = "data";
  @SerializedName(SERIALIZED_NAME_DATA)
  @javax.annotation.Nonnull
  private Object data;

  public OnlineCheck() {
  }

  public OnlineCheck rid(@javax.annotation.Nonnull Integer rid) {
    
    this.rid = rid;
    return this;
  }

  /**
   * Get rid
   * @return rid
   */
  @javax.annotation.Nonnull

  public Integer getRid() {
    return rid;
  }


  public void setRid(@javax.annotation.Nonnull Integer rid) {
    this.rid = rid;
  }

  public OnlineCheck data(@javax.annotation.Nonnull Object data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull

  public Object getData() {
    return data;
  }


  public void setData(@javax.annotation.Nonnull Object data) {
    this.data = data;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnlineCheck onlineCheck = (OnlineCheck) o;
    return Objects.equals(this.rid, onlineCheck.rid) &&
        Objects.equals(this.data, onlineCheck.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rid, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnlineCheck {\n");
    sb.append("    rid: ").append(toIndentedString(rid)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  public void writeToParcel(Parcel out, int flags) {
    out.writeValue(rid);
    out.writeValue(data);
  }

  OnlineCheck(Parcel in) {
    rid = (Integer)in.readValue(null);
    data = (Object)in.readValue(null);
  }

  public int describeContents() {
    return 0;
  }

  public static final Parcelable.Creator<OnlineCheck> CREATOR = new Parcelable.Creator<OnlineCheck>() {
    public OnlineCheck createFromParcel(Parcel in) {
      return new OnlineCheck(in);
    }
    public OnlineCheck[] newArray(int size) {
      return new OnlineCheck[size];
    }
  };

}

